name: example
description: Example App for "HEY SD READER"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hey_sd_reader:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides: 
  hey_sd_reader: 
    path: ../

flutter:
  uses-material-design: true
